spring:
  application:
    name: Api-Gateway

  cloud:
    gateway:
      routes:
        - id: USER-AUTHENTICATION-SERVICE
          uri: http://localhost:8080/
          predicates:
            - Path=/registration
            - Path=/genToken


        - id: LIBRARIAN-PROFILE
          uri: http://localhost:8081/
          predicates:
            - Path=/api/library-profiles/**


        - id: BOOK-MANAGEMENT
          uri: http://localhost:8082/
          predicates:
            - Path=/api/books/**


        - id: BOOKING-STATUS
          uri: http://localhost:8083/
          predicates:
            - Path=/api/books/**


server:
  port: 3333
